export * from './types';
export * from './data/school';
export * from './data/programs';
export * from './data/facilities';
export * from './data/achievements';
export * from './data/activities';
export * from './data/news';
export * from './data/ppdb';
export * from './data/contact';
